# Generated by Django 2.2.8 on 2020-01-29 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
